/**
 * viewer.js — Auto Assault model viewer.
 *
 * Serve the repo root over HTTP and open /tools/model-viewer/:
 *   python -m http.server 8080     (from the repo root)
 *   http://localhost:8080/tools/model-viewer/
 *
 * Reads index.json (generated by tools/build_viewer_index.py), fetches raw .geo
 * files, parses them in-browser (geo-parser.js) and renders each GPCE section
 * with its own material (materials.js), including live vehicle paint tinting.
 */

import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { parseGeo } from './geo-parser.js';
import { TextureBank, buildMaterial, isShadowEffect, TINT_DEFAULTS } from './materials.js';

const ROOT = '../../'; // page lives at /tools/model-viewer/

// --- DOM ---------------------------------------------------------------------
const el = (id) => document.getElementById(id);
const listEl = el('model-list');
const searchEl = el('search');
const countEl = el('count');
const lodEl = el('lod');
const shadowsEl = el('show-shadows');
const wireframeEl = el('wireframe');
const texturesEl = el('textures');
const bboxEl = el('show-bbox');
const tintRow = el('tint-row');
const tintSchemeEl = el('tint-scheme');
const tintPrimaryEl = el('tint-primary');
const tintSecondaryEl = el('tint-secondary');
const infoEl = el('info');
const statusEl = el('status');

// --- three.js scaffold (lighting rig from bounty-hunter-physics.html) --------
const renderer = new THREE.WebGLRenderer({ antialias: true });
renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure = 1.2;
el('canvas-wrap').appendChild(renderer.domElement);

const scene = new THREE.Scene();
scene.background = new THREE.Color(0x10141c);
scene.fog = new THREE.FogExp2(0x10141c, 0.002);

const camera = new THREE.PerspectiveCamera(55, 1, 0.05, 4000);
camera.position.set(4, 2.5, 5);

const controls = new OrbitControls(camera, renderer.domElement);
controls.enableDamping = true;
controls.dampingFactor = 0.08;

const sun = new THREE.DirectionalLight(0xfff2e0, 2.4);
sun.position.set(6, 10, 4);
scene.add(sun);
scene.add(new THREE.AmbientLight(0x404860, 0.9));
scene.add(new THREE.HemisphereLight(0x9db4ff, 0x3a2f24, 0.55));

const grid = new THREE.GridHelper(20, 20, 0x2a3242, 0x1c2230);
grid.position.y = 0;
scene.add(grid);

function resize() {
  const w = renderer.domElement.parentElement.clientWidth;
  const h = renderer.domElement.parentElement.clientHeight;
  renderer.setSize(w, h);
  camera.aspect = w / h;
  camera.updateProjectionMatrix();
}
window.addEventListener('resize', resize);

renderer.setAnimationLoop(() => {
  controls.update();
  renderer.render(scene, camera);
});

// --- state --------------------------------------------------------------------
let index = null;
let bank = null;
let current = null;      // { entry, parsed, group, boxHelper }
let filterResults = [];

const state = {
  lod: 0,
  showShadows: false,
  wireframe: false,
  textures: true,
  showBbox: false,
  tintScheme: null,
  primary: null,          // [r,g,b] override from pickers
  secondary: null,
};

// --- model list ----------------------------------------------------------------
const LIST_LIMIT = 400;

function applyFilter() {
  const q = searchEl.value.trim().toLowerCase();
  const models = index.models;
  filterResults = q
    ? models.filter((m) => m.name.toLowerCase().includes(q))
    : models;
  countEl.textContent = `${filterResults.length.toLocaleString()} / ${models.length.toLocaleString()} models`;
  renderList();
}

function renderList() {
  listEl.textContent = '';
  const frag = document.createDocumentFragment();
  for (const entry of filterResults.slice(0, LIST_LIMIT)) {
    const li = document.createElement('li');
    li.textContent = entry.name;
    li.title = `${entry.path} (${(entry.size / 1024).toFixed(0)} KB)`;
    if (current && current.entry === entry) li.classList.add('active');
    li.addEventListener('click', () => loadModel(entry));
    frag.appendChild(li);
  }
  if (filterResults.length > LIST_LIMIT) {
    const li = document.createElement('li');
    li.className = 'more';
    li.textContent = `… ${(filterResults.length - LIST_LIMIT).toLocaleString()} more — refine the search`;
    frag.appendChild(li);
  }
  listEl.appendChild(frag);
}

// --- model loading / building ---------------------------------------------------
async function loadModel(entry) {
  setStatus(`Loading ${entry.name}…`);
  try {
    const res = await fetch(ROOT + entry.path);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const buf = await res.arrayBuffer();
    const parsed = parseGeo(buf);
    if (!parsed.sections.length) throw new Error('no renderable sections');

    disposeCurrent();
    current = { entry, parsed, group: null, boxHelper: null };

    // Default view state per model: LOD 0, per-model tint defaults.
    state.lod = 0;
    state.tintScheme = null;
    state.primary = null;
    state.secondary = null;

    rebuild({ refit: true });
    updateModelControls();
    history.replaceState(null, '', `#${encodeURIComponent(entry.name)}`);
    setStatus('');
  } catch (e) {
    setStatus(`Failed to load ${entry.name}: ${e.message}`, true);
  }
  renderList();
}

function disposeCurrent() {
  if (!current) return;
  if (current.group) {
    scene.remove(current.group);
    current.group.traverse((o) => {
      if (o.isMesh) {
        o.geometry.dispose();
        o.material.dispose();
      }
    });
  }
  if (current.boxHelper) scene.remove(current.boxHelper);
  current = null;
}

function visibleSections() {
  if (!current) return [];
  return current.parsed.sections.filter((s) =>
    s.lod === state.lod && (state.showShadows || !isShadowEffect(s.effect)));
}

function rebuild({ refit = false } = {}) {
  if (!current) return;
  if (current.group) {
    scene.remove(current.group);
    current.group.traverse((o) => {
      if (o.isMesh) {
        o.geometry.dispose();
        o.material.dispose();
      }
    });
  }
  if (current.boxHelper) {
    scene.remove(current.boxHelper);
    current.boxHelper = null;
  }

  const group = new THREE.Group();
  const infos = [];
  for (const section of visibleSections()) {
    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute('position', new THREE.BufferAttribute(section.positions, 3));
    if (section.normals) geometry.setAttribute('normal', new THREE.BufferAttribute(section.normals, 3));
    if (section.uvs) geometry.setAttribute('uv', new THREE.BufferAttribute(section.uvs, 2));
    geometry.setIndex(new THREE.BufferAttribute(section.indices, 1));
    if (!section.normals) geometry.computeVertexNormals();

    const { material, info } = buildMaterial(section, bank, {
      tintScheme: state.tintScheme,
      primary: state.primary,
      secondary: state.secondary,
      texturesEnabled: state.textures,
    });
    material.wireframe = state.wireframe;
    infos.push({ section, info });

    group.add(new THREE.Mesh(geometry, material));
  }
  scene.add(group);
  current.group = group;
  current.infos = infos;

  if (state.showBbox) {
    current.boxHelper = new THREE.BoxHelper(group, 0x5588ff);
    scene.add(current.boxHelper);
  }
  if (refit) fitCamera(group);
  renderInfo();
}

function fitCamera(group) {
  const box = new THREE.Box3().setFromObject(group);
  if (box.isEmpty()) return;
  const center = box.getCenter(new THREE.Vector3());
  const sphere = box.getBoundingSphere(new THREE.Sphere());
  const r = Math.max(sphere.radius, 0.1);
  const dir = new THREE.Vector3(0.75, 0.45, 1).normalize();
  camera.position.copy(center).addScaledVector(dir, r * 2.4);
  camera.near = Math.max(r / 500, 0.01);
  camera.far = Math.max(r * 50, 100);
  camera.updateProjectionMatrix();
  controls.target.copy(center);
  grid.position.y = box.min.y;
}

// --- per-model UI -----------------------------------------------------------------
function updateModelControls() {
  const lods = [...new Set(current.parsed.sections.map((s) => s.lod))].sort((a, b) => a - b);
  lodEl.textContent = '';
  for (const lod of lods) {
    const opt = document.createElement('option');
    opt.value = String(lod);
    opt.textContent = `LOD ${lod}`;
    lodEl.appendChild(opt);
  }
  lodEl.value = String(state.lod);
  lodEl.disabled = lods.length <= 1;

  // Tint controls when any visible section is tintable.
  const tintInfo = (current.infos ?? []).find(({ info }) => info.tintable);
  if (tintInfo) {
    tintRow.style.display = '';
    const schemes = tintInfo.info.tintSchemes ?? [];
    tintSchemeEl.textContent = '';
    for (const nn of schemes) {
      const opt = document.createElement('option');
      opt.value = nn;
      opt.textContent = `Scheme ${nn}`;
      tintSchemeEl.appendChild(opt);
    }
    tintSchemeEl.value = state.tintScheme ?? schemes[0];
    const p = state.primary ?? paramColor(tintInfo.section.params, 'MatColorPrimary', TINT_DEFAULTS.primary);
    const s = state.secondary ?? paramColor(tintInfo.section.params, 'MatColorSecondary', TINT_DEFAULTS.secondary);
    tintPrimaryEl.value = rgbToHex(p);
    tintSecondaryEl.value = rgbToHex(s);
  } else {
    tintRow.style.display = 'none';
  }
}

function paramColor(params, name, fallback) {
  const v = params[name];
  return Array.isArray(v) && v.length >= 3 ? v.slice(0, 3) : fallback;
}

function rgbToHex([r, g, b]) {
  const h = (x) => Math.round(Math.min(1, Math.max(0, x)) * 255).toString(16).padStart(2, '0');
  return `#${h(r)}${h(g)}${h(b)}`;
}

function hexToRgb(hex) {
  return [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255);
}

// --- info panel --------------------------------------------------------------------
function renderInfo() {
  if (!current) { infoEl.textContent = ''; return; }
  const { entry, parsed, infos } = current;
  const shown = infos.map(({ section }) => section);
  const verts = shown.reduce((n, s) => n + s.vertexCount, 0);
  const tris = shown.reduce((n, s) => n + s.triangleCount, 0);
  const effects = [...new Set(shown.map((s) => s.effect).filter(Boolean))];
  const resolved = [...new Set(infos.flatMap(({ info }) => info.textures))];
  const missing = [...new Set(infos.flatMap(({ info }) => info.missing))];
  const allLods = [...new Set(parsed.sections.map((s) => s.lod))];
  const shadows = parsed.sections.filter((s) => isShadowEffect(s.effect)).length;

  const line = (label, value) => `<div><span class="k">${label}</span> ${value}</div>`;
  let html = '';
  html += line('model', entry.name);
  html += line('sections', `${shown.length} shown / ${parsed.sections.length} total (${allLods.length} LODs${shadows ? `, ${shadows} shadow` : ''})`);
  html += line('geometry', `${verts.toLocaleString()} verts, ${tris.toLocaleString()} tris`);
  if (effects.length) html += line('effects', effects.join(', '));
  if (resolved.length) html += line('textures', resolved.join(', '));
  if (missing.length) html += `<div class="warn"><span class="k">missing</span> ${missing.join(', ')}</div>`;
  if (parsed.warnings.length) html += `<div class="warn"><span class="k">warnings</span> ${parsed.warnings.join('; ')}</div>`;
  infoEl.innerHTML = html;
}

function setStatus(msg, isError = false) {
  statusEl.textContent = msg;
  statusEl.classList.toggle('error', isError);
}

// --- events --------------------------------------------------------------------------
searchEl.addEventListener('input', applyFilter);
lodEl.addEventListener('change', () => { state.lod = parseInt(lodEl.value, 10) || 0; rebuild(); });
shadowsEl.addEventListener('change', () => { state.showShadows = shadowsEl.checked; rebuild(); });
wireframeEl.addEventListener('change', () => { state.wireframe = wireframeEl.checked; rebuild(); });
texturesEl.addEventListener('change', () => { state.textures = texturesEl.checked; rebuild(); });
bboxEl.addEventListener('change', () => { state.showBbox = bboxEl.checked; rebuild(); });
tintSchemeEl.addEventListener('change', () => { state.tintScheme = tintSchemeEl.value; rebuild(); });
tintPrimaryEl.addEventListener('input', () => { state.primary = hexToRgb(tintPrimaryEl.value); rebuild(); });
tintSecondaryEl.addEventListener('input', () => { state.secondary = hexToRgb(tintSecondaryEl.value); rebuild(); });
window.addEventListener('keydown', (e) => {
  if (e.key === '/' && document.activeElement !== searchEl) {
    e.preventDefault();
    searchEl.focus();
  }
});

// --- boot ------------------------------------------------------------------------------
async function boot() {
  resize();
  setStatus('Loading index.json…');
  try {
    const res = await fetch('./index.json');
    if (!res.ok) throw new Error(`HTTP ${res.status} — run: python tools/build_viewer_index.py`);
    index = await res.json();
  } catch (e) {
    setStatus(`Could not load index.json: ${e.message}`, true);
    return;
  }
  bank = new TextureBank(index.textures, ROOT);
  applyFilter();
  setStatus('');

  // Deep link: #<model-name>
  const hash = decodeURIComponent(location.hash.slice(1));
  if (hash) {
    const entry = index.models.find((m) => m.name === hash);
    if (entry) loadModel(entry);
  } else {
    const buggy = index.models.find((m) => m.name === 'obj_veh_p_h_r_cha_02_dune-buggy.geo');
    if (buggy) loadModel(buggy);
  }
}
boot();
